# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c029002f1536fea58599bd1d14cb830787350942347b9dff39c6aa2e2b74ca2e743f2ee52de3459dee4c163cf70102652a74cbd1122c122a23e47e9a5daa710e

test:
  secret_key_base: 132c9a88a01283453994b836450170bf4510b0ee13cd47bb3f68095d6caef087bfe6c649ada3c62fea9fd4e652229f5759a7bc0d1b584f399ed99937438630fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
